// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsP4Giptq9psBE1R2T2QirSYawtODww6s',
    appId: '1:451064993988:web:cdc7a3f35df69184965191',
    messagingSenderId: '451064993988',
    projectId: 'ecommerce-app-abda5',
    authDomain: 'ecommerce-app-abda5.firebaseapp.com',
    storageBucket: 'ecommerce-app-abda5.appspot.com',
    measurementId: 'G-PDEKZXBLF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcXz9Gj58TwLdEMtxvJ33SktxLdRQrvc',
    appId: '1:451064993988:android:d12f614fc950b567965191',
    messagingSenderId: '451064993988',
    projectId: 'ecommerce-app-abda5',
    storageBucket: 'ecommerce-app-abda5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsP4Giptq9psBE1R2T2QirSYawtODww6s',
    appId: '1:451064993988:web:1a934dcf091ef39e965191',
    messagingSenderId: '451064993988',
    projectId: 'ecommerce-app-abda5',
    authDomain: 'ecommerce-app-abda5.firebaseapp.com',
    storageBucket: 'ecommerce-app-abda5.appspot.com',
    measurementId: 'G-F3LD7QN2N0',
  );
}
